### ISSUE TITLE
[12.0 Account Asset] Entry Sequence Number ignored when posting asset moves

### ISSUE THREAD

**Issue by treviser** [OCA/account-financial-tools#1008]
Situation:
Migrated Odoo instance. Asset profiles are correctly specified and assigned to a particular journal for asset moves. This journal has its own entry sequence properly defined and assigned.

![Selection_288](https://user-images.githubusercontent.com/1814941/83964453-8f95f700-a8ad-11ea-88d3-9420589d2550.png)

Issue:
When posting journal entries from the asset management module, the entry sequence of the journal is ignored and the name of the asset itself is posted to the journal entry name:

![Selection_289](https://user-images.githubusercontent.com/1814941/83964636-9a04c080-a8ae-11ea-8f62-5da327a48d9e.png)

The 2 older entries before were created on Odoo 9.0 before the migration using the original Odoo asset module.

Expected Behaviour:

Then Number (field "name") should contain the sequence value (ANL/2019/xxxx) instead of the asset name.

**Comment by luc-demeyer** [comment]
There is no legal requirement to have subsequent numbering for asset postings. The current behaviour is on purpose since it makes it easier to cancel and repost asset lines.
The _setup_move_data method allows you to change this behaviour and call the journals sequence.
This issue has been posted several times already in the past and comes back on a regular basis in my own customer base but with proper explanation my customers usually prefer the current behaviour.

**Comment by treviser** [comment]
@luc-demeyer Thanks for your feedback and the explanation.
