### ISSUE TITLE
account_lock_date_update: Po files not generated

### ISSUE THREAD

**Issue by cubells** [OCA/account-financial-tools#1024]
I'm interested in translate this module to Spanish and I see that po files are not generated:

https://github.com/OCA/account-financial-tools/tree/11.0/account_lock_to_date/i18n

In any version. 

And I can't see how can I help to translate here:

https://translation.odoo-community.org/projects/account-financial-tools-11-0/account-financial-tools-11-0-account_lock_to_date/

Does It exist a problem?

**Comment by marcelsavegnago** [comment]
Did you try to start the Spanish translation via the translation platform?

https://odoo-community.org/page/translate
https://docs.weblate.org/en/latest/user/translating.html

I just started translation into Portuguese pt_BR normally.
![image](https://user-images.githubusercontent.com/3595132/87062521-84532580-c1e3-11ea-8fa8-1f3b4990bba8.png)

**Comment by Shide** [comment]
This module seems to be duplicated.
`account_lock_to_date` and `account_lock_date_update` seems the same module but `account_lock_to_date` seems to overwrite with another fields the base account behavior.

I think this module (`account_lock_date_update`) is the right one because only adds a wizard to the behavior.
