### ISSUE TITLE
Which approach account_fiscal_year v14

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#1069]
The `account.fiscal.year` model has been moved to EE in https://github.com/odoo/odoo/pull/46110

In v8 and before, we had fiscal years and periods, we relied on that. In v9 and v10, `account_fiscal_year` had its own data model because fiscal years were not supported in Odoo. In v11, v12, v13, we relied on the upstream Odoo model. In v14 this model still exists but has moved to EE... sigh.

This is particularly annoying because it cripples the ability for community reports depending on fiscal year data to produce correct results. We could recreate our own data model, but then people installing OCA reports on EE would get wrong results unless they populate the community data model.

Perhaps we should first do an inventory of OCA modules that depend on it ?

**Comment by sbidoul** [comment]
`mis-builder` needs [res.company.compute_fiscalyear_dates](https://github.com/OCA/mis-builder/blob/38148d6ff9e85904b02c47cc9d82a064d38c497a/mis_builder/models/aep.py#L272-L274).

**Comment by luc-demeyer** [comment]
account_asset_management relies on fiscal years.

**Comment by pedrobaeza** [comment]
I think we have to restore OCA's `account_fiscal_year` module, but extracting the code from core v13, so we only need to add the dependency, but not changing the code in dependent modules.

**Comment by rvalyi** [comment]
Hello I agree with @pedrobaeza about making a basic v13 port. Also when porting previously open source Odoo SA modules to the OCA, I suggest to stick with the newest official Odoo Enterprise data model whenever possible. I believe having the same tables and columns when this is trivial is no licensed code infringement and instead it minimizes the diff with the Odoo official doc, it also makes migration with Odoo EE easier and improves our eco-system compatibility.

With this in mind I just check the v14 fiscal year data model and it seems there is no change in v14:
![Screenshot from 2020-10-11 11-30-43](https://user-images.githubusercontent.com/16926/95681412-163d4680-0bb6-11eb-9b30-d059a1dee57e.png)

**Comment by michaelkarrer81** [comment]
> Hello I agree with @pedrobaeza about making a basic v13 port. Also when porting previously open source Odoo SA modules to the OCA, I suggest to stick with the newest official Odoo Enterprise data model whenever possible. I believe having the same tables and columns when this is trivial is no licensed code infringement and instead it minimizes the diff with the Odoo official doc, it also makes migration with Odoo EE easier and improves our eco-system compatibility.

+1 - I also think it would be best to stick to the newest odoo data model.

**Comment by legalsylvain** [comment]
> I think we have to restore OCA's account_fiscal_year module, but extracting the code from core v13, so we only need to add the dependency, but not changing the code in dependent modules.

:+1: (in fact I don't see other options). 

@fpodoo : It seems you are full closing accounting features gradually. Could you explain the next steps of your roadmap ? 
Thanks !

**Comment by sbidoul** [comment]
+1 to keep the same model as long as we can, of course.

What do we do with the methods, such as `compute_fiscalyear_dates` ?

@fpodoo in case you read this, I for one usually don't complain loudly when features move around and indeed it is no surprise that some accounting stuff moves to EE. Yet there was a kind of untold agreement that basic data models that are required for basic interop of accounting modules would stay in CE. `account.fiscal.year` is one of them, since if it diverges between EE and CE, unsuspecting users well get different results when running, e.g. EE and OCA reports. This will create bad user experiences.

**Comment by fpodoo** [comment]
> @fpodoo <https://github.com/fpodoo> : It seems you are full closing
> accounting features gradually. Could you explain the next steps of your
> roadmap ?
>
I have no idea why we did that for this specific object / feature. But I
can answer on our mindset:

We have some apps in Odoo Community and others in Enterprise. The apps that
are in Odoo Community stays in
community (and all their future features are published open source) and the
apps in Enterprise stays in Enterprise:
we might have exceptions [1] but we try to stick to that rules.
- Invoicing is an app in Odoo Community
- Accounting is an app in Odoo Enterprise

So, all improvements we do on Invoicing are published in LGPL, and all
improvements we do on Accounting are done
in Enterprise.

I didn't check into the details, but I don't think we removed user features
from community: nothing visible from the UI
as it was not used by the Invoiving app. The issue is more for third-party
modules than for users.

But we might move code for maintainability: if a code is not used in Odoo
Community and requires a refactoring, we
prefer to refactor in OE directly rather than splitting our refactoring in
two, or playing with multiple inheritances as the
features is split in two repositories. It's probably the reason why we did
that to account.fiscal.year.

-- 
Fabien

[1] https://www.odoo.com/blog/odoo-news-5/post/odoo-community-enterprise-532

>

**Comment by OSevangelist** [comment]
@fpodoo i think your answer is well understandable, but if you consider "Odoo Community" as always only the official community version of yours w/o any OCA code, the OCA can't rely on any base architecture any longer, because that would naturally read as "If some model or feature is not used by Odoo CE official code, it may be eventually moved to Odoo EE even if it was CE code in the first place". This relatively small change for you, increases friction, frustration and double work not only among integrators but also among users. I doubt that this would be beneficial to anybody in the end. So honestly is there any chance you overrule that decision and take it back, than i think this would be the time to do it. Thanks for considering!

**Comment by jcdrubay** [comment]
@Frederik Kramer: +1

**Comment by OSevangelist** [comment]
> @frederik Kramer: +1
> […](#)
> On Thu, Oct 15, 2020 at 4:03 PM Frederik Kramer ***@***.***> wrote: @fpodoo <https://mailtrack.io/trace/link/c5579afdfc27f3d75d5fdcbdc8871b8549532fd7?url=https%3A%2F%2Fgithub.com%2Ffpodoo&userId=5008176&signature=de1f94ea3f2dca09> i think your answer is well understandable, but if you consider "Odoo Community" as always only the official community version of yours w/o any OCA code, the OCA can't rely on any base architecture any longer, because that would naturally read as "If some model or feature is not used by Odoo CE official code, it may be eventually moved to Odoo EE even if it was CE code in the first place". This relatively small change for you, increases friction, frustration and double work not only among integrators but also among users. I doubt that this would be beneficial to anybody in the end. So honestly is there any chance you overrule that decision and take it back, than i think this would be the time to do it. Thanks for considering! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://mailtrack.io/trace/link/e6f4354bdfb45d13eee5c83a0ed1b7dfbc2ddda9?url=https%3A%2F%2Fgithub.com%2FOCA%2Faccount-financial-tools%2Fissues%2F1069%23issuecomment-709017019&userId=5008176&signature=34bd50da598b3ea4>, or unsubscribe <https://mailtrack.io/trace/link/e20e0ad8bbd520f7277a0c93b45d7b16b83ec398?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANPALHV6E2M7OW2S3UT5XLSK23FFANCNFSM4SLUXAEA&userId=5008176&signature=d70c059c5c62dfcc> .

Who is that ;-)

**Comment by fpodoo** [comment]
> @fpodoo <https://github.com/fpodoo> i think your answer is well
> understandable, but if you consider "Odoo Community" as always only the
> official community version of yours w/o any OCA code, the OCA can't rely on
> any base architecture any longer, because that would naturally read as "If
> some model or feature is not used by Odoo CE official code, it may be
> eventually moved to Odoo EE even if it was CE code in the first place".
> This relatively small change for you, increases friction, frustration and
> double work not only among integrators but also among users. I doubt that
> this would be beneficial to anybody in the end. So honestly is there any
> chance you overrule that decision and take it back, than i think this would
> be the time to do it. Thanks for considering!
>
We won't revert back, because we consider it a good decision.

I think it's good for your OCA module too; It won't benefit you to have a
dead, legacy, code to rely on. Because if the
code is not used in OC, it won't be maintained efficiently either. By
putting the object in your module, at least you can
maintain it efficiently.

Sorry, but our priority is code quality, rather than maintaining legacy
code to help third party modules. Fortunately, we won't
have a lot of use case like this in the future; the only area where we have
such issue in the accounting app, so it's limited.

-- 
Fabien

**Comment by jakubPCV** [comment]
Standing by your point even though it is proven to make life difficult for partners and end users. Happens too often with Odoo. You should really work on your approach and mindset.

If needed,  I can show tens of of support tickets when Odoo made a wrong decision in terms of business workflow changes in Odoo and never owned up to their mistakes and fuckups → and was never willing to resolve anything.

**Comment by pedrobaeza** [comment]
@jakubPCV even if true, this thread is not for general rantings, but focused on the topic of the title, so I'm folding these comments.

**Comment by jakubPCV** [comment]
Is there any thread on general ranting with someone in power? I find it
very hard to find someone to discuss feedbacks regarding roadmaps,
functionality, planned and done changes amd performance of support team

**Comment by pedrobaeza** [comment]
Clearly not here in OCA, as your rants seems to be with Odoo S. A. Write to your account manager.

**Comment by jakubsmolka** [comment]
Wish that could help anything. But sorry for spamming OCA, that was not
my intention
