### ISSUE TITLE
account_check_deposit : why not using same as v8 bank statement

### ISSUE THREAD

**Issue by lucmaurer** [OCA/account-financial-tools#154]
Hello,
I don't understand why the check_deposit module doesn't use the same mechanism as the v8 bank_statement ?

I think check_deposit is not different than a bank_statement with a specific check journal and perhaps a specific report.
I understand that we could have a new menu, but I think the form should be the same than the v8 bank statement with the same way of reconcilation.

What do you think ?

Luc

**Comment by sebastienbeau** [comment]
Hi Luc, great to see you on github ;)
First of all this module have been design on 6.1 and then ported to 7 and 8. We maybe can make some change for 8.
For the reconciliation we initially didn't use the bank_statement because the bank statement didn't get the behaviour needed for the check_deposit.

The aim of the check_deposit is to select a group of customer "check" then to create a "check_deposit" with it. And when the check deposit is created we generate one account move.

For exemple: 
I have two check
one for 100€ (in France debit 5112 chèque à encaissé)
and one for 200€ (in France debit 5112 chèque à encaissé)

I will create a check deposit for 300€ this will generate two account_move_line
- one in the credit  (in France 512 chèque à encaissé)
- one for the debit (in France 512 banque or 5112XX chèque remise en banque (if you use an intermediary account))

Then I reconcile my account 5112 with the account move lien 100, 200 and 300.

I will think more but I am not sure that we can do it with the object bank statement (it's not so easy to change the behaviour of this object). But maybe we can found an alternative way to work with bank-statement on v8. How do you see the process using the native bank statement?

**Comment by lucmaurer** [comment]
Hello Seb,

Many thanks for your answer.

If I understand well that mean that you decide when you create the invoice that your customer will pay by check. For me a check is "just" a payment mode. We could imagine create an invoice and we don't know the payment mode he will use.

My scenario was:
- create the invoice (we don't know how he will pay)
- we receive a check
- we create a check deposit and add a new line => we just put: date, amount, partner, référence (check number)
- after that I will reconcile my check with my invoice

But you are right, this will not create only 2 ML,but 2 ML per bank statement line => perhaps it is 2 different thing. My scenario should use the bank statement and your the check deposit.

Regards

**Comment by sebastienbeau** [comment]
Ok, I understand.
The check deposit is not used for creating the payment, but for the deposit to the bank.
In my case I have two step. First step is registring the payment (most of the time my customer use the module sale_quick_payment to register a payment from the sale order). This payment will generate an account move line from the customer account (411 in France) to the check account (5112 in France). So in my case the invoice will be paid with this payment. (you can also use the account.voucher module to generate this payment)
Then the check deposit is just here to generate a report and a account_move with the total of the deposit and to reconcile this deposit with the payment generated before.

Note : I have some customer that do 3x payment by check, for that they register 3 check on the sale order (or invoice) and then each month they select the check they want to give to the bank

Hope my explication are understandable ;)
