### ISSUE TITLE
Currency rate update module, Cannot convert anymore since 2015-03-04

### ISSUE THREAD

**Issue by falinwa** [OCA/account-financial-tools#179]
Hi,

Since march 5 2015, we cannot convert anymore.
The service that we used is Yahoo.
Is there something wrong?

2015-03-02 04:32:35 currency updated.  
2015-03-03 04:33:24 currency updated.  
2015-03-04 04:33:07 currency updated.  
2015-03-05 04:47:25 ERROR : could not convert string to float: N/A
2015-03-06 04:33:22 ERROR : could not convert string to float: N/A
2015-03-07 04:33:12 ERROR : 'Yahoo_getter' object has no attribute 'MOD_NAME'
2015-03-08 04:33:14 ERROR : could not convert string to float: N/A
2015-03-09 04:33:28 ERROR : could not convert string to float: N/A
2015-03-10 04:33:34 ERROR : could not convert string to float: N/A
2015-03-11 04:32:30 ERROR : could not convert string to float: N/A
2015-03-12 04:33:04 ERROR : could not convert string to float: N/A
2015-03-13 04:39:38 ERROR : could not convert string to float: N/A
2015-03-14 04:32:27 ERROR : 'Yahoo_getter' object has no attribute 'MOD_NAME'
2015-03-15 04:39:24 ERROR : could not convert string to float: N/A
2015-03-16 04:32:52 ERROR : 'Yahoo_getter' object has no attribute 'MOD_NAME'
2015-03-17 04:32:43 ERROR : could not convert string to float: N/A
2015-03-18 04:32:59 ERROR : could not convert string to float: N/A
2015-03-19 04:33:10 ERROR : could not convert string to float: N/A
2015-03-20 04:33:07 ERROR : 'Yahoo_getter' object has no attribute 'MOD_NAME'
2015-03-21 04:36:39 ERROR : 'Yahoo_getter' object has no attribute 'MOD_NAME'
2015-03-22 04:36:58 ERROR : could not convert string to float: N/A
2015-03-23 04:36:51 ERROR : could not convert string to float: N/A
2015-03-24 04:33:20 ERROR : could not convert string to float: N/A
2015-03-24 04:33:23 ERROR : could not convert string to float: N/A
2015-03-25 04:32:53 ERROR : could not convert string to float: N/A
2015-03-26 04:33:05 ERROR : could not convert string to float: N/A
2015-03-27 04:32:40 ERROR : could not convert string to float: N/A
2015-03-28 04:33:23 ERROR : could not convert string to float: N/A
2015-03-29 04:39:34 ERROR : could not convert string to float: N/A
2015-03-30 04:40:30 ERROR : could not convert string to float: N/A
2015-03-31 04:33:20 ERROR : could not convert string to float: N/A

**Comment by falinwa** [comment]
Both for version 7 and version 8 doesn't work anymore.
Our country is in China.
Is this issue just happen to us?

I check that only Yahoo that not worked.

**Comment by dstags-LO** [comment]
We are experiencing the same issue. Any news on this?

**Comment by falinwa** [comment]
yes, we still waiting too, right now we just change the web services that we used.
Yahoo is not worked anymore.

**Comment by dstags-LO** [comment]
Since we are unable to wait for a resolution, we dug into the code and fixed this issue. 

It appears that the original URL utilized by the Yahoo API is no longer valid as manually calling it returns a 404 error. Reading into the API, I've reformatted the URL to properly return the csv file used for parsing the rate. Below is a snippet of the code I changed in currency_rate_update.py to get this working properly.

```
def get_updated_currency(self, currency_array, main_currency, max_delta_days):
    """implementation of abstract method of Curreny_getter_interface"""
    self.validate_cur(main_currency)
    #url='http://download.finance.yahoo.com/d/quotes.txt?s="%s"=X&f=sl1c1abg'
    url='http://download.finance.yahoo.com/d/quotes.csv?s=%s=X&f=sl1c1abg'
```

**Comment by Jeelkhanpara** [comment]
I check manually this url='http://download.finance.yahoo.com/d/quotes.csv?s=%s=X&f=sl1c1abg'
it shows in .csv file
 =X N/A N/A N/A N/A N/A
it means Not Available.

**Comment by dstags-LO** [comment]
%s is the variable passed into the URL intended to represent the currency you are trying to get a quote for. The reason it is returning N/A is because it doesn't know what currency you are trying to get rates for. 

See This note:

Using YQL with the Yahoo Finance table (yahoo.finance.quotes) linked by NT3RP, currencies appear with symbol="ISOCODE=X", for example: "ARS=X" for Argentine Peso, "AUD=X" for Australian Dollar. "USD=X" doesn't exist, but it would be 1, since the rest are rates against USD

So a properly formed URL would return rates in the csv assuming you pass in a currency. Try this:

http://download.finance.yahoo.com/d/quotes.csv?s=EUR=X&f=sl1c1abg (Note: I replaced the %s with EUR to return the current FX for EUR against USD which always equals 1.

Hope it helps. Our chages to the code have been working perfectly for nearly a month.

**Comment by Jeelkhanpara** [comment]
hi,I Set url as you suggest , but log shows
 !!! 2015-06-03 18:16:27.890209 not all arguments converted during string formatting !!! 
My main currency is INR and Not Update any Currency Rate.

Have you change code in other area.

**Comment by Jeelkhanpara** [comment]
Have you any idea for me.what to do for currency rate update?.
Please Help me...

**Comment by dstags-LO** [comment]
Since INR is the currency you are trying to get rates for, manually try this URL by copying and pasting into your browser window. It should return a csv file containing the FX for INR using USD as the base currency where USD = 1.

http://download.finance.yahoo.com/d/quotes.csv?s=INR=X&f=sl1c1abg

Steps:

1) Find your currency_rate_update module located in your addons directory under openerp. (In my case it is located in /opt/openerp/addons/currency_rate_update). 
2) Within the module, open currency_rate_update.py and locate the Yahoo_getter class. 
3) Find the get_updated_currency function and edit the URL. (I've placed the code below)
4) save, close, and reload the module

When you complete this, if it still doesn't work, please send along a log trace for further review.

Here is the entire class as it exists in my implementation:

#Yahoo ###################################################################################
class Yahoo_getter(Curreny_getter_interface) :
    """Implementation of Currency_getter_factory interface
    for Yahoo finance service"""

```
def get_updated_currency(self, currency_array, main_currency, max_delta_days):
    """implementation of abstract method of Curreny_getter_interface"""
    self.validate_cur(main_currency)
    #url='http://download.finance.yahoo.com/d/quotes.txt?s="%s"=X&f=sl1c1abg'
    url='http://download.finance.yahoo.com/d/quotes.csv?s=%s=X&f=sl1c1abg'
    if main_currency in currency_array :
        currency_array.remove(main_currency)
    for curr in currency_array :
        self.validate_cur(curr)
        res = self.get_url(url%(main_currency+curr))
        val = res.split(',')[1]
        if val :
            self.updated_currency[curr] = val
        else :
            raise Exception('Could not update the %s'%(curr))

    return self.updated_currency, self.log_info  # empty string added by polish changes
```

**Comment by Jeelkhanpara** [comment]
Here is the class as it exists in my implementation openerp v5:
#Yahoo ###################################################################################  
class Yahoo_getter(Curreny_getter_interface) :
    """Implementation of Currency_getter_factory interface
    for Yahoo finance service"""

```
def get_updated_currency(self, currency_array, main_currency):
    """implementation of abstract method of Curreny_getter_interface"""
    self.validate_cur(main_currency)

    url='http://download.finance.yahoo.com/d/quotes.csv?s="INR"&f=sl1c1ab'
    if main_currency in currency_array :
        currency_array.remove(main_currency)
    for curr in currency_array :
        self.validate_cur(curr)
        res = self.get_url(url%(main_currency+curr))
        val = res.split(',')[1]
        if val :
            self.updated_currency[curr] = val
        else :
            raise Exception('Could not update the %s'%(curr))

    return self.updated_currency, self.log_info  # empty string added by polish changes
```

and Log is 

 currency updated at 2015-02-23 14:41:45.762483  
 currency updated at 2015-02-24 14:12:09.816829  
 currency updated at 2015-02-25 14:33:09.548328  
 currency updated at 2015-02-26 14:00:01.881651  
 currency updated at 2015-02-27 14:00:18.836724  
 currency updated at 2015-02-28 13:57:08.293352  
 currency updated at 2015-03-01 13:57:10.236598  
 currency updated at 2015-03-02 13:57:12.629513  
 currency updated at 2015-03-03 13:56:49.216760  
 currency updated at 2015-03-04 13:56:53.489923  
 !!! 2015-03-05 14:05:30.771612 invalid literal for float(): N/A !!!
 !!! 2015-03-06 14:39:53.518634 invalid literal for float(): N/A !!!
 !!! 2015-03-07 13:59:09.583830 invalid literal for float(): N/A !!!
 !!! 2015-03-31 13:59:34.978732 invalid literal for float(): N/A !!!
 !!! 2015-04-09 14:11:45.734716 invalid literal for float(): N/A !!!
 !!! 2015-04-10 14:19:30.560043 'Yahoo_getter' object has no attribute 'MOD_NAME' !!!
 !!! 2015-04-11 14:03:06.669076 invalid literal for float(): N/A !!!
 !!! 2015-04-12 14:18:29.537300 invalid literal for float(): N/A !!!
 !!! 2015-04-13 14:00:18.545623 invalid literal for float(): N/A !!!
 !!! 2015-04-15 14:59:50.817912 invalid literal for float(): N/A !!!
 !!! 2015-04-16 13:59:55.011081 invalid literal for float(): N/A !!!
 !!! 2015-04-17 14:00:41.699551 invalid literal for float(): N/A !!!
 !!! 2015-04-18 14:19:04.202124 'Yahoo_getter' object has no attribute 'MOD_NAME' !!!
 !!! 2015-04-19 14:01:02.140207 invalid literal for float(): N/A !!!
 !!! 2015-04-20 14:00:49.288238 invalid literal for float(): N/A !!!
 !!! 2015-04-27 13:56:35.228880 invalid literal for float(): N/A !!!
 !!! 2015-04-28 13:59:38.645442 invalid literal for float(): N/A !!!
 !!! 2015-04-29 14:21:21.182386 invalid literal for float(): helvetica !!!
 !!! 2015-04-30 13:59:44.457909 invalid literal for float(): helvetica !!!
 !!! 2015-05-01 14:37:14.150637 invalid literal for float(): helvetica !!!
 !!! 2015-06-03 17:48:33.648049 not all arguments converted during string formatting !!!
 !!! 2015-06-03 17:50:42.925380 not all arguments converted during string formatting !!!
 !!! 2015-06-03 17:57:01.522261 could not convert string to float: N/A !!!
 !!! 2015-06-03 17:58:03.300027 not all arguments converted during string formatting !!!
 !!! 2015-06-03 18:03:36.877545 cannot import name xpath !!!
 !!! 2015-06-03 18:03:53.787360 cannot import name xpath !!!
 !!! 2015-06-03 18:03:54.935934 cannot import name xpath !!!
 !!! 2015-06-03 18:04:08.931734 not all arguments converted during string formatting !!!
 !!! 2015-06-03 18:07:05.658250 not all arguments converted during string formatting !!!
 !!! 2015-06-03 18:13:13.776442 unsupported format character 'I' (0x49) at index 52 !!!
 !!! 2015-06-03 18:14:10.710144 not all arguments converted during string formatting !!!
 !!! 2015-06-03 18:14:31.730713 cannot import name xpath !!!
 !!! 2015-06-03 18:16:16.884433 cannot import name xpath !!!
 !!! 2015-06-04 15:05:08.922863 not all arguments converted during string formatting !!!
 !!! 2015-06-04 15:06:43.378952 cannot import name xpath !!!
 !!! 2015-06-04 15:08:56.892056 not all arguments converted during string formatting !!!
 !!! 2015-06-04 15:26:25.902607 not all arguments converted during string formatting !!! Test
INR
[2015-06-04 18:56:19,293][dc_2015_05_03] INFO:cron-rates:not all arguments converted during string formatting

i deleted some the line because more long file.
when I see in currency are it's not any update.it show last date update 03/04/2015.

**Comment by dstags-LO** [comment]
Change your function call in the yahoo getter class (See my previous post above) to the code I've pasted below. Your error is because it is trying to identify where to insert the variable into the URL call and can not find the insert point which is represented by a %s. The URL you have formatted is also missing =X so it is improperly formatting your URL for calling Yahoo. Also, you are running v5 and I am running v7 so while it is unlikely, there is a possibility it will not work as I've not tested in anything other than v7.

def get_updated_currency(self, currency_array, main_currency):
    """implementation of abstract method of Curreny_getter_interface"""
    self.validate_cur(main_currency)

```
url='http://download.finance.yahoo.com/d/quotes.csv?s=%s=X&f=sl1c1abg'
if main_currency in currency_array :
    currency_array.remove(main_currency)
for curr in currency_array :
    self.validate_cur(curr)
    res = self.get_url(url%(main_currency+curr))
    val = res.split(',')[1]
    if val :
        self.updated_currency[curr] = val
    else :
        raise Exception('Could not update the %s'%(curr))

return self.updated_currency, self.log_info  # empty string added by polish changes
```

**Comment by falinwa** [comment]
I think this must be merge with the fix?

**Comment by rossigee** [comment]
The hostname 'download.finance.yahoo.com' no longer resolves. The Yahoo getter should probably be removed/replaced.
