### ISSUE TITLE
8.0 currency_rate_update: failed update blocks all future updates

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-financial-tools#301]
I am experiencing this issue with several customers in v8.0 that use currency_rate_update with a simple configuration:
- 1 service provider
- cron activated with a daily frequency
  If, for some strange reasons, the field next_run is not correctly updated on one particular run (I still need to understand exactly why), the future runs will fail because of the line of code:

```
services = self.search([('next_run', '=', fields.Date.today())])
```

This is a new behavior of v8, it was not like that in v7. It is causing at lot of failures with my v8 customers that use currency_rate_update in production. Maybe we should change this line of code by:

```
services = self.search([('next_run', '<=', fields.Date.today())])
```

So that, if one run started by cron fails (and next_run is not correctly updated), then the next runs started by cron will be executed. What do you think ?

**Comment by feketemihai** [comment]
@alexis-via Hi Alexis, yes i think this is a good sollution, it was already spotted by @dhongu in https://github.com/odoo-romania/l10n-romania/issues/76 when we started to use the ported module to v8, but not enough time to make the PR.

The ideea is how to handle the recompute of the next_run field, since the calculation is from old value of next_run plus the interval, let's say you will have a daily scheduler, and in this case the next_run value will still remain in past, if you will not update it manually...

https://github.com/OCA/account-financial-tools/blob/8.0/currency_rate_update/model/currency_rate_update.py#L319

**Comment by feketemihai** [comment]
@alexis-via It is because the service is launched, but if you have a frecvency of 1 week, month, this will not respect the date that you want...let's say you want to update on monday's...the service doesn't launch on monday...so you will not get the right rate...it is launched then on tuesday...so you will get the wrong rate...but it will compute the next_run to the next monday...

**Comment by pedrobaeza** [comment]
But I don't get why we need to change next_run manually on each run. Why just simply change the frequency and other static parameters when configuring the update?

**Comment by feketemihai** [comment]
@pedrobaeza You don't need to change it manually, it's computed when the cron is executed...only in the situation when the cron doesn't finish...the value will remain the same...

**Comment by pedrobaeza** [comment]
That's why I'm saying. Cron itself can update this value, why making that manually?

**Comment by feketemihai** [comment]
With the fix, changing the "=" to "<=" it will change the next_run, but like i said, it will get you a wrong rate when using week, monthly frecvency and if you are using daily the next_run will remain always in the past...

**Comment by alexis-via** [comment]
@pedrobaeza I agree with your question. I don't understand the advantages of this new code with the next_run parameter ; I would prefer to remove it altogether than just make my small stupid patch. We should ask the author of the code to explain us why he developped it like that.

**Comment by feketemihai** [comment]
I ported the module to V8 and in V7 the only option to configure the rate frecvency was to modify the cron frecvency, in V8 the cron will be launched daily and update the rates on the frecvency that you set in the service...because if you have 2 services, one that you want to do it daily, the other monthly in V7 you had 2 crons, in V8 only one cron that will update all the services based on next_run value from the service...

**Comment by pedrobaeza** [comment]
Well, that can be a reason, although it's very weird that you set different frequencies for the services, but why then rely on next_run and not create a field on each service definition to store last run instead? You only have to check if last_run + frequency <= today.

**Comment by feketemihai** [comment]
Yes...but on a weekly scheduler on monday which was not executed you will still get the wrong value...a rate from tuesday...and last_run  + frecvency will get you the tuesday's rates instead on mondays...

**Comment by pedrobaeza** [comment]
I'm not worried about that: you are providing the correct rate for the correct rate, although with a jump. Providing a way to notify the admin and to retrieve a rate for a specific date, the circle is closed.

Even thinking your fully-automated scheme, you just simply run multiple times between last_run + frequency date to today incrementing each time the frequency required, but breaking the loop when one update fails.

**Comment by feketemihai** [comment]
That's why i used the "=", but probably it's worth to compute next_run even if the cron fails with an error...so you will not get the rate for that date but you will have the next_run correctly...what do you think?

**Comment by pedrobaeza** [comment]
I think you shouldn't touch next_run and let the cron work as usual, and play with the other variable as I'm mentioning.
