### ISSUE TITLE
Asset Management : create an asset per product item

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/account-financial-tools#413]
Currently, it's not possible to create an asset per product item if there are more than one item of a product on the same invoice line.

Let me take an exemple:

If I have an invoice line for 10 quantity of DELL Latitude E6540. it's not possible to have one asset per computer. In this case, it's more correct to have one asset per item because each life cycle can be different.

A solution will be to split each quantity on a new invoice line ... or how to break the related purchase workflow ...

So, I want to implement a solution that allow to create an asset per quantity in the same invoice line.

At the first look on the code of `account-financial-tools/account_asset_management/account_move.py`, I'm afraid that it would be difficult to make a generic solution for this case ...

@luc-demeyer any comment or thinking about that ?

Thanks,

Adrien

**Comment by luc-demeyer** [comment]
I have this exact same case in our install base.

We currently work around it by different techniques:

1)      normal purchase on interim or  expense account for the purchase of the computers, followed by a ‘miscellaneous’ accounting entry which credits the account gaused for the purchase and has a debit asset account per laptop.

2)      For some customers we have linked the asset module with a ‘physical’ asset management module (a  module  which tracks cars, computers cell phones, …).

When one of the assets comes to an end before the full end of the single asset, a compensation asset is created.

In order to cope with this in a clean way, we could adapt the account_asset _management module with a kind of “split” function (like the ‘split’ button in the stock management module).

This would be a bit of work, hence I would be in favour to do it on the V10 port of the account_asset_management module.

I also encountered several times the reverse demand: merge several purchases into a single asset, hence we need both a ‘split’ and a ‘merge’ function.

**Comment by adrienpeiffer** [comment]
Hi Luc,

Thanks for your answer.

What do you think about the possibility to split the invoice line with one account move line per product item automatically? This behavior won't modify the asset management process. Also, we can imagine to have a parameter to set that directly in the asset category. So, if we have an invoice line with a category which is marked as 'Split invoice line per product item'. The validation of this invoice will create one account move line per product item and one asset per item (per move line) will be created automatically.

**Comment by luc-demeyer** [comment]
Looks ok to me.
Don't forget to document this new parameter in the README.rst.

**Comment by adrienpeiffer** [comment]
Solution provides by #417
