### ISSUE TITLE
currency_rate_update

### ISSUE THREAD

**Issue by Aivenho** [OCA/account-financial-tools#623]
Could be nice to implement EUR rates for ECB non-supported currencies from this free service http://www.floatrates.com/daily/eur.xml.

**Comment by pedrobaeza** [comment]
Thanks for the suggestion. The way for expressing a wishlist / suggestion is to put a PR for adding it in the module README in the section "Known issues / Roadmap", so that developers or other contributors can see it and take it into account. See https://odoo-community.org/page/code for a brief explanation on how to do it.

Meanwhile, I close this issue, as they are more intended for reflecting problems, bugs or totally new specifications.
