### ISSUE TITLE
Tax matching issues with account_chart_update

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#662]
Hi,

I've tested account_chart_update for taxes and fiscal positions on 10/11 with l10n_be

My main issue I have is with the criteria used to match taxes.

https://github.com/OCA/account-financial-tools/blob/69b55288e7d62a24537fd9b83bb5b95b9cbab1e6/account_chart_update/wizard/wizard_chart_update.py#L249-L254

Since the description field is not unique and is sometimes the same as the tax name there are wrong matches. I think we should have a stricter matching mechanism for taxes as the current method is dangerous.

@pedrobaeza do you have an opinion on this?

**Comment by pedrobaeza** [comment]
The problem here is the lack of an unique field for matching templates with their correspondent equivalents. I think we can push for v12 to have a `code` field in both for avoiding these problems, but meanwhile, we need to match on both due to the history of the `l10n_es` module, with a lot of changes in these fields until I normalized it (more or less) on OCA/l10n-spain#144. The problem is that a lot of people continues having these old data in their instances or they change it due to OCA/l10n-spain#675, so removing one of these conditions will make this to fail.

**Comment by sbidoul** [comment]
We could an option in the wizard to activate "fuzzy matching" on taxes and have an exact matching on tax name by default.

**Comment by pedrobaeza** [comment]
OK, but please activate it by default. Will you help me on getting the codes on master?

**Comment by sbidoul** [comment]
Have you seen there is a unique key on tax names now?

**Comment by pedrobaeza** [comment]
The problem is that 3 fields is the desirable thing to have:

* A code that is not shown anywhere except on the model, that it's not susceptible of being changed and without translations issue.
* A name for showing in x2many fields & name_get/name_search for using in the UI by the users. This field is translatable.
* A description for putting on the reports, also translatable.

The translatable thing is specially annoying on the matching thing.

**Comment by sbidoul** [comment]
I always wondered why taxes do not preserve a link to their template.

**Comment by pedrobaeza** [comment]
Yeah, that's another option for master instead of the code...

**Comment by sbidoul** [comment]
Let's push for having that in 12.

**Comment by pedrobaeza** [comment]
Yes, I agree it's the best approach.

**Comment by sbidoul** [comment]
@pedrobaeza this!

https://github.com/odoo/odoo/blob/12a97cc7add28ce7081b158c9bcbfae1b86e5600/addons/account/models/chart_template.py#L350-L358

It looks like objects created from chart template retain can be traced to their template object through an xmlid convention.

**Comment by pedrobaeza** [comment]
Well, it's a very indirect method for getting it, but if it's the only one right now... For how long this has been? Since v9? On migrated DBs (or created manually records), it won't serve, so an alternative match is still needed.

**Comment by sbidoul** [comment]
@pedrobaeza it is v11 only. But this means a request to link taxes to their template or adding a tax code will be rejected, because the link exists through the tax xmlid.

**Comment by pedrobaeza** [comment]
@sbidoul for solving your problem meanwhile, you can add a matching option on the wizard for selecting which method to use (name, description, both...). I will investigate the matching by XML-ID.
