### ISSUE TITLE
account_move_batch_validate does not post in date order

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#79]
Hello,

While playing around with account_move_batch_validate, I noticed it does not post moves in chronological order.

The problem is similar with account_move_validation_improvement.

The official wizard has an order by 'date'.

I believe this can create issues in some situations. However this is not easy to resolve in a multi-worker environment, or in the presences of retries.

What are your thoughts about this? cc/ @nbessi @gurneyalex @lepistone

**Comment by sbidoul** [comment]
I propose #80 to improve account_move_validation_improvement.

**Comment by lepistone** [comment]
Hi @sbidoul. For `account_move_batch_validate`, I agree with you that specifying `order` in the searches would help, and it is a good change to make. 

On the other hand, jobs are created and scheduled, and I don't think we can guarantee that the order of creation of the jobs will be respected.

In fact, one of the use cases of the module is to validate a large quantity of moves, and keep going if one has a problem. That clearly does not preserve the order because the problematic one will be fixed and confirmed afterwards.

**Comment by sbidoul** [comment]
@lepistone indeed we can't guarantee ordering of jobs.

I was thinking of doing the posting in three passes instead of two:
1. mark moves to post (as it is now)
2. create one job per journal to assign numbers to moves, with order by date
3. create one job per move to post

Even if the posting jobs are done in random order, the numbering will be respected.

Makes sense?

**Comment by lepistone** [comment]
@sbidoul I am unsure on this one.

At the moment the module should handle the case where you change your mind or add other lines when jobs are running. Also, jobs can be run again for the same lines before they are completely treated with no ill effects. So, at a first glance, your approach could work, but it looks like there are many brittle edge cases to test.

I'll ping @guewen: have you have had a situation where you want to preserve ordering somewhat?

Thanks!

**Comment by nbessi** [comment]
@lepistone we can play with priority of the jobs. we may convert date to seconds or something like that and use it as priority

**Comment by lepistone** [comment]
ah, ok, thanks @nbessi. I think priority and right order from the start are good as a best-effort approach, but I'm not sure whether we can guarantee ordering, because one of the use cases we had in mind for the module was to handle problems manually later (incorrect moves that could be manually fixed, or deleted, or postponed) and there is concurrency, too.

**Comment by nbessi** [comment]
@lepistone I agreed it is more a workaround and more workers you have the more odds to have unordered task may come. Connector does not provided such features out of the box we have to extends it to add it. Like having workoers to have access to all queue, channels etc... 

I have same needs for connector_odbc  seems to be quite a work

**Comment by sbidoul** [comment]
@guewen @lepistone I'm back on this topic.

I'm not sure I understand the corner cases mentioned by @lepistone in https://github.com/OCA/account-financial-tools/issues/79#issuecomment-63506427 . The approach I propose would not really change the logic of the module except it would at a numbering pass before marking the moves for posting.

But I may miss use cases you have. 

IMO it would be much cleaner to preserve numbering by date.

I'd like your advice before embarking on a PR for adding the numbering behaviour.

**Comment by lepistone** [comment]
@sbidoul use cases that look difficult (not impossible) to me:
- user selects a million lines, marks them, then changes his mind and deselects some or all
- for some reason, the process is run again when there are still pending jobs to treat the same lines.

In general, we could have in any moment lines that have not been treated at all, lines that were assigned a number but not confirmed yet, and so on.

I am not saying this is not possible or a bad idea, just that this needs some thinking about all the cases that could occur.
